### ISSUE TITLE
Fig 5 repro attempt: logging details and augmented Lagrangian params 

### ISSUE THREAD

**Issue by ekernf01** [Genentech/dcdfg#2]
Hi DCD-FG devs! With a coworker, I am trying to reproduce parts of fig. 5 from the DCD-FG paper. Here are our results from the interferon condition.

![Bar plot showing negative log likelihood contributions of test-set regimes with wide spread and DCD-FG beating but overlapping linear baselines](https://user-images.githubusercontent.com/5271803/208464406-d7e5adfe-5610-47c0-b909-e561efce139e.png)

(DCD-FG is green, bottom)

The relative performance is the same as fig 5:

![Bar plot showing negative log likelihood contributions of test-set regimes with narrow spread and DCD-FG winning cleanly](https://user-images.githubusercontent.com/5271803/208464775-482006dc-d7d3-41db-8f84-24213ff4f9cc.png)

(DCD-FG is red, top)

But the median NLL is lower, and the spread much higher, than fig 5. We want to check in on two details. 

- Is each dot in fig5 the negative log likelihood for a single cell in the test data, or an average of single-cell NLL's within an interventional condition, or an average of all test set cells across one of many data splits? We're currently logging the second (average within condition).
- We encountered an error with NaNs during mlplr training. To solve it and finish training, three different strategies have worked for us. 
    1) cap the mlplr training at 200 epochs, 
    2) uncomment lines affecting the augmented lagrangian param updates ([model L150](https://github.com/Genentech/dcdfg/blob/7ad08e8262de0b075a086fa2a70bf0432969a4d4/dcdfg/lowrank_mlp/model.py#L150) leads to [model L181](https://github.com/Genentech/dcdfg/blob/7ad08e8262de0b075a086fa2a70bf0432969a4d4/dcdfg/lowrank_mlp/model.py#L181)) or 
    3) change to double precision. 
    
My colleague's example figure (above) caps mlplr at 200 epochs, but we will likely next default to option two, uncommenting. What would you recommend?

Thank you very much!

**Comment by ekernf01** [comment]
We believe these minor differences are due to a different random initialization, and of the 3 options above, we have chosen to use double precision.

**Comment by rvinas** [comment]
@ekernf01 I am also trying to reproduce the results and had similar questions. I have found your comments really useful, thank you so much for providing your insights. Regarding your first question, did you figure out what the spread of box plot represents? Also, do you happen to know or have some code to calculate the I-MAE and plot the network of Figure 6?

**Comment by ekernf01** [comment]
I'm sorry, I don't have code to calculate MAE or plot networks. I spoke with Romain around this time and he was incredibly helpful to my project, but I don't remember if we discussed the x-axis of this specific plot.
